### ISSUE TITLE
Apps aren't loaded yet.

### ISSUE THREAD

**Issue by m-misseri** [shtalinberg/django-amp-tools#1]
Hello,
I'm trying to use your app, but does not work.

I'm using django 1.8.5.

Let me know,
Thanks.

Log errors:
```
(ve-fast)daniaax@MacBook:~/Sites/test/test/test/test$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/core/management/__init__.py", line 177, in fetch_command
    commands = get_commands()
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/core/management/__init__.py", line 72, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/Users/daniaax/Sites/test/ve-fast/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by shtalinberg** [comment]
Show me you INSTALLED_APPS setting in the settings.py, MIDDLEWARE_CLASSES and TEMPLATES setting in settings.py.

**Comment by m-misseri** [comment]
Here you go, thanks.

```
INSTALLED_APPS += (
    # Database migration helpers:
    'social.apps.django_app.default',
    'compressor',
    'django.contrib.sitemaps',
    'djcelery',
    'redactor',
    'corsheaders',
    'amp_tools',
)
```
```
MIDDLEWARE_CLASSES = (
    # Default Django middleware.
    'django.middleware.cache.UpdateCacheMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myproject.middleware.AccountNotConfirmedMiddleware',
    'myproject.middleware.NoMailMiddleware',
    'myproject.middleware.UpdateLastActivityMiddleware',
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'myproject.middleware.UserUidMiddleware',
    'amp_tools.middleware.AMPDetectionMiddleware',
)
```

```
TEMPLATE_LOADERS = (
    'amp_tools.loader.Loader',
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)
```

**Comment by shtalinberg** [comment]
1. try:
```
INSTALLED_APPS += (
    # Database migration helpers:
    'social.apps.django_app.default',
    'django.contrib.sitemaps',
    'amp_tools',
    'djcelery',
    'redactor',
    'corsheaders',
    'compressor',
)
```

2. try:
```
MIDDLEWARE_CLASSES = (
    # Default Django middleware.
    'django.middleware.cache.UpdateCacheMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'amp_tools.middleware.AMPDetectionMiddleware',
    'myproject.middleware.AccountNotConfirmedMiddleware',
    'myproject.middleware.NoMailMiddleware',
    'myproject.middleware.UpdateLastActivityMiddleware',
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
    'myproject.middleware.UserUidMiddleware',
    'myproject.middleware.PostQuestionOnMTurkMiddleware',    
)
```

3. try disable cache middlewares

**Comment by m-misseri** [comment]
same errors

**Comment by shtalinberg** [comment]
https://travis-ci.org/shtalinberg/django-amp-tools   - all version django>=1.8 with many python version tests passed/ 
It's only problem with you project settings or other 3-rd app

**Comment by shtalinberg** [comment]
Version 0.1.1 used on our site http://bergsoftplus.com from requirements without any changes
http://bergsoftplus.com/weblog/2016/11/28/internet-bezopasnost-pri-onlajn-pokupkah-20/?amp-content=amp

**Comment by shtalinberg** [comment]
I add doc for usage  https://github.com/shtalinberg/django-amp-tools/blob/develop/docs/usage.rst   maybe it help you

**Comment by pepourquier** [comment]
Hi,

same issue with django 1.9.

I tried to remove middleware and loader or remove the order but it does not work.

**Comment by aanimation** [comment]
@shtalinberg im read th docs for thousands, but didnot successfull, im really stressed. is there video or step-by-step (basic) or simple sample project (python27 and python3) ? pls.
i just newbie on django python, and do frontend :(

**Comment by aanimation** [comment]
hahahaha...its working...
```
<title>{% if request.is_amp_detect %}AMP{% endif %} {% block title %}{% endblock %} | WEB</title>
 <link rel="amphtml" href="/?amp-content=amp" />
```

and now, how to passing my amp html template to folder /amp ? anyone can help me?

my all template current in template folder

**Comment by shtalinberg** [comment]
0.2.0    - tested with  Django 1.11
